apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      tier: app
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
      labels:
        app: search
        tier: app
        version: v1
    spec:
      containers:
        - name: search
          image: ghcr.io/academey/distributed_tracing_shopping_mall-search:main
          imagePullPolicy: Always
          env:
          - name: PURCHASE_PORT
            value: "8002"
          - name: PURCHASE_HOST
            value: "purchase"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
    - port: 8001
      protocol: TCP
  selector:
    app: search
  type: ClusterIP

---
# error version search
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-error-version
spec:
  selector:
    matchLabels:
      app: search
  replicas: 1
  template: 
    metadata:
      labels:
        app: search
        version: error
    spec:
      containers:
      - name: search
        image: ghcr.io/academey/distributed_tracing_shopping_mall-search:error
        imagePullPolicy: Always
        env:
        - name: PURCHASE_PORT
          value: "8002"
        - name: PURCHASE_HOST
          value: "purchase" 
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-for-the-search-service
spec:
  host: search.default.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      maxEjectionPercent: 50
      consecutive5xxErrors: 2
      interval: 10s
      baseEjectionTime: 30s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase
spec:
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: ghcr.io/academey/distributed_tracing_shopping_mall-purchase:main
          imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          ports:
            - containerPort: 8002
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: purchase
spec:
  type: NodePort
  ports:
    - port: 8002
      nodePort: 31002
      protocol: TCP
  selector:
    app: purchase

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: ghcr.io/academey/distributed_tracing_shopping_mall-frontend:main
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: SEARCH_HOST
            value: "search"
          - name: SEARCH_PORT
            value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
      tier: app
      version: v1
  template:
    metadata:
      labels:
        app: loadgenerator
        tier: app
        version: v1
    spec:
      containers:
        - name: loadgenerator
          image: ghcr.io/academey/distributed_tracing_shopping_mall-loadgenerator:main
          imagePullPolicy: Always
          env:
          - name: API_ENDPOINT
            value: "http://search:8001/metrics-test"