apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search   
          image: ghcr.io/academey/distributed_tracing_shopping_mall-search:main
          imagePullPolicy: Always
          env:
            - name: PURCHASE_PORT
              value: "8002"
            - name: PURCHASE_HOST
              value: "purchase"
          livenessProbe:
            httpGet:
              path: /
              port: 8001
          readinessProbe:
            httpGet:
              path: /
              port: 8001
          ports:
            - containerPort: 8001
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  type: NodePort
  ports:
    - port: 8001
      nodePort: 31001
      protocol: TCP
  selector:
    app: search

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase
spec:
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: ghcr.io/academey/distributed_tracing_shopping_mall-purchase:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8002
          readinessProbe:
            httpGet:
              path: /
              port: 8002
          ports:
            - containerPort: 8002
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: purchase
spec:
  type: NodePort
  ports:
    - port: 8002
      nodePort: 31002
      protocol: TCP
  selector:
    app: purchase

