apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search
spec:
  rules:
    - host: search.192.168.64.3.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search
                port:
                  number: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: search
      tier: app
      version: v1
  template:
    metadata:
      labels:
        app: search
        tier: app
        version: v1
    spec:
      containers:
        - name: search
          image: ghcr.io/academey/distributed_tracing_shopping_mall-search:main
          imagePullPolicy: Always
          env:
          - name: PURCHASE_PORT
            value: "8002"
          - name: PURCHASE_HOST
            value: "purchase"
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  ports:
    - port: 8001
      protocol: TCP
  selector:
    app: search
    tier: app
    version: v1
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: search
# spec:
#   selector:
#     matchLabels:
#       app: search
#   template:
#     metadata:
#       labels:
#         app: search
#     spec:
#       containers:
#         - name: search   
#           image: ghcr.io/academey/distributed_tracing_shopping_mall-search:main
#           imagePullPolicy: Always
#           env:
#             - name: PURCHASE_PORT
#               value: "8002"
#             - name: PURCHASE_HOST
#               value: "purchase"
#           livenessProbe:
#             httpGet:
#               path: /
#               port: 8001
#           readinessProbe:
#             httpGet:
#               path: /
#               port: 8001
#           ports:
#             - containerPort: 8001
#               protocol: TCP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: search
# spec:
#   type: NodePort
#   ports:
#     - port: 8001
#       nodePort: 31001
#       protocol: TCP
#   selector:
#     app: search

# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase
spec:
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: ghcr.io/academey/distributed_tracing_shopping_mall-purchase:main
          imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8002
          ports:
            - containerPort: 8002
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: purchase
spec:
  type: NodePort
  ports:
    - port: 8002
      nodePort: 31002
      protocol: TCP
  selector:
    app: purchase

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: server
          image: ghcr.io/academey/distributed_tracing_shopping_mall-frontend:main
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: SEARCH_HOST
            value: "search"
          - name: SEARCH_PORT
            value: "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: loadgenerator
      tier: app
      version: v1
  template:
    metadata:
      labels:
        app: loadgenerator
        tier: app
        version: v1
    spec:
      containers:
        - name: loadgenerator
          image: ghcr.io/academey/distributed_tracing_shopping_mall-loadgenerator:main
          imagePullPolicy: Always
          env:
          - name: SEARCH_PORT
            value: "8001"
          - name: SEARCH_HOST
            value: "search"
          - name: SLEEP_TIMEOUT
            value: 0.5